### ISSUE TITLE
how could the IMD cutoff be evaluated as value 1

### ISSUE THREAD

**Issue by phoebe-xin-leung** [AlexandrovLab/SigProfilerClusters#18]
When I applied SigPfofilerClusters to a TCGA sample, I got the results shown below. The IMD cutoff seems to be evaluated as 1. Did I use in a wrong way ?

this is the command:

from SigProfilerSimulator import SigProfilerSimulator as sigSim
sigSim.SigProfilerSimulator(project='TCGA', project_path='/.../sigprofiler/TCGA/', genome='GRCh38', contexts=['96'], simulations=100)
from SigProfilerClusters import SigProfilerClusters as hp
hp.analysis(project='TCGA', genome='GRCh38', contexts='96', simContext=['96'], input_path='/.../sigprofiler/TCGA/', subClassify=True, includedVAFs=True, includedCCFs=False, TCGA=True, sanger=False)

this is the process of detection of IMD
![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/75560375/4f0a3709-5c8c-4bbc-886d-6d23dbb424c2)
this is the dectection of clustered events
![image](https://github.com/AlexandrovLab/SigProfilerClusters/assets/75560375/9febb8e4-14f3-40d7-82d2-0de94c691ca2)

**Comment by MousumyCSE** [comment]
Hi @phoebe-xin-leung,

Thanks for reaching out. I think, the way you are running is correct. Can I ask you to send me the log files? And is it a WGS or WES data?

Best,
Mousumy

**Comment by ebergstr** [comment]
Hi,

Apologies for the delay!

This sample appears to be a hyper-mutated sample. From a statistical perspective, there is an issue in determining whether mutations are truly clustering as the result of a singular mutational event or have not happened as a result of repeated mutagenesis within a given region due to the high mutation load. SigProfilerClusters is essentially telling you that, within this sample, any clustered event could have happened by chance and cannot be statistically separated from the non-clustered mutations.

As this is not directly related to an on-going issue with the tool, I will close this issue. Please feel free to open an additional issue if you encounter any other problems.

Please note that the SBS-96 plots in your sample are currently displaying the wrong number of mutations. We are aware of this and are working on an update to be released in the next 1-2 weeks.

Best,
Erik
