### ISSUE TITLE
Program always exits with no logging or error message

### ISSUE THREAD

**Issue by eallen-bbi** [AlexandrovLab/SigProfilerClusters#8]
After creating output files using SigProfilerSimulator, sigProfilerClusters always exits with no plots, no error log, and no error messages.  Sometimes changing the project name will make the program go further in the process, but still no plots, error log, or error messages.  Here's an example of what I've tried running:

hp.analysis("OUTNEW", "GRCh37", "96", ["288"], ".", analysis="all", sortSims=True, subClassify=True, correction=True, calculateIMD=True, TCGA=True, sanger=False).  The folder contains only one VCF, which is the BRCA example VCF from the Wiki site.

**Comment by ebergstr** [comment]
Hi,

One quick suggestion is to use the full path to your project directory rather than using the current working directory ("/[path_to_project]/ instead of ".") or to simply add a backslash to your path ("./"). 

If this does not fix your issue, can you please provide additional information as to your current environment for running SigProfilerClusters? Specifically, the python version, SigProfilerCluster version, and whether you are running on a computing cluster or on a local machine (and the operating system)? Further can you provide the output in the logs file associated with SigProfilerSimulator?

Thanks.

**Comment by eallen-bbi** [comment]
Hi Erik,

OK, I tried the full path, both with and without the ending slash and get same results - program just exists after.  I think the VCF is actually being read for some some steps, as its updating files in the simulation folder and vcf_corrected.  Again, the only VCF in the folder is BRCA-UK_SP116353.snv_mnv.vcf.

Also, here's the other info you requested:

Python 3.8.13
Name: SigProfilerClusters
Version: 1.0.8

Running on a single ubuntu node, version  Ubuntu 20.04.3 LTS

I'll need to regenerate the Simulator logs - but didn't get any errors during that step.

>>> hp.analysis("OUTNEW", "GRCh37", "96", ["288"], "/path omitted/users/eallen/SigProfilerTest", analysis="all", sortSims=True, subClassify=True, correction=True, calculateIMD=True, TCGA=True, sanger=False)


Beginning SigProfilerClusters Analysis

Calculating mutational distances...Completed!
Determining sample-dependent intermutational distance (IMD) cutoff...Completed!

Analyzing clustered mutations...

Then, if I run it again, no changes to command line, it doesn't show any messages at all - just stops.

The log file "SigProfilerClusters_OUTNEW_GRCh37_2022-04-26.err" can be seen in the logs folder, but it can't be accessed - perhaps the file is still open.

I may try to run on a different Linux system to see if I get same results.

Thanks,
Eric

**Comment by eallen-bbi** [comment]
Update: I was able to get this working on a different Linux system.  The prior system had some storage setup issues, and it was silently crashing when certain chmod actions were taken during execution.  Can close this issue.
